aks

diff --git a/.github/workflows/build_and_deploy_to_aks.yml b/.github/workflows/build_and_deploy_to_aks.yml
--- a/.github/workflows/build_and_deploy_to_aks.yml
+++ b/.github/workflows/build_and_deploy_to_aks.yml
@@ -30,6 +30,18 @@ jobs:
           docker build -t $ACR_LOGIN_SERVER/myapp:${{ github.event.inputs.releaseTag }} .
           docker push $ACR_LOGIN_SERVER/myapp:${{ github.event.inputs.releaseTag }}
 
+      - name: Pull and Verify Docker Image
+        run: |
+          docker pull $ACR_LOGIN_SERVER/myapp:${{ github.event.inputs.releaseTag }}
+          docker create --name temp-container $ACR_LOGIN_SERVER/myapp:${{ github.event.inputs.releaseTag }}
+          if ! docker cp temp-container:/usr/share/nginx/html/welcome.html welcome.html; then
+            echo "welcome.html not found in the image" && exit 1
+          fi
+          if ! docker cp temp-container:/usr/share/nginx/html/thankyou.html thankyou.html; then
+            echo "thankyou.html not found in the image" && exit 1
+          fi
+          docker rm temp-container
+
       - name: Replace image tag in Kubernetes deployment file
         run: |
           sed -i "s|kalidynamics2024.azurecr.io/myapp:RELEASE_TAG_PLACEHOLDER|$ACR_LOGIN_SERVER/myapp:${{ github.event.inputs.releaseTag }}|" .github/kubernetes/aks_deployment.yaml
